#!/bin/bash
#SBATCH -N 1
#SBATCH --time 01:00:00
#SBATCH -p normal

cd $HOME/LGMeval
source /home/raymond/miniconda3/bin/activate LGM

nproc=24

###############
# Atmosphere
###############
mpirun -n $nproc python process/atm/hist.py
mpirun -n 1 python process/atm/calcadd.py
mpirun -n $nproc python process/atm/avg_mon2seas.py
mpirun -n $nproc python process/atm/avg_mon2ann.py
#mpirun -n $nproc python process/atm/trends.py
#mpirun -n $nproc python process/atm/timeseries.py

###############
# Sea ice
###############
#mpirun -n $nproc python process/ice/hist.py

###############
# Ocean
###############
#mpirun -n $nproc python process/ocn/hist.py
